[package]
name = "pistoncore-input"
version = "1.0.1"
edition = "2018"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["keyboard", "mouse", "input", "piston"]
description = "A structure for user input"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/piston.git"
homepage = "https://github.com/PistonDevelopers/piston"
documentation = "https://docs.rs/pistoncore-input"

[lib]
name = "input"
path = "src/lib.rs"

[features]
serde = ["dep:serde", "dep:serde_derive"]
test = ["serde", "dep:serde_json"]

[dependencies]
serde_derive = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true, default-features = false }
serde_json = { version = "1.0", optional = true }
bitflags = "1.0.0"
piston-viewport = "1.0.0"

